# Generated by Django 3.0.14 on 2025-04-05 07:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.IntegerField(default=0)),
                ('firstName', models.CharField(default='', max_length=250)),
                ('lastName', models.CharField(default='', max_length=250)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
