# Generated by Django 3.0.14 on 2025-04-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cit410signupApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registercourse',
            name='studentID',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
