# Generated by Django 3.0.14 on 2025-04-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cit410signupApp', '0002_auto_20250405_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registercourse',
            name='studentID',
            field=models.IntegerField(default=0),
        ),
    ]
